# Generated by Django 2.0.1 on 2018-01-27 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=20)),
                ('User_Name', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('CPassword', models.CharField(max_length=20)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Transgender', 'Transgender')], max_length=20)),
                ('Mobile_Number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('\\+?\\d[\\d -]{8,12}\\d', 'Please enter valid contact number')])),
                ('Day', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], max_length=2)),
                ('Month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10)),
                ('Year', models.CharField(max_length=4)),
                ('Address', models.TextField()),
                ('Pin_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^[0-9]*$', 'enter valid number')])),
                ('Country', models.CharField(max_length=20)),
                ('E_mail', models.CharField(max_length=40)),
                ('prev_cons', models.TextField(verbose_name='Previous Consulting Details')),
                ('Appointment_type', models.CharField(choices=[('Heart Checkup', 'Heart Checkup'), ('Eye Checkup', 'Eye Checkup'), ('Hearing Test', 'Hearing Test'), ('Blood Test', 'Blood Test'), ('Normal Consulting', 'Normal Consulting'), ('Skin Care', 'Skin Care')], max_length=20)),
            ],
        ),
    ]
